on: [pull_request]
name: Static analysis
jobs:
  phpstan:
    name: PHPStan
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.4

      - name: Download dependencies
        uses: ramsey/composer-install@v2

      - name: Install PHPStan
        uses: ramsey/composer-install@v2
        with:
          composer-options: "--working-dir=tools/phpstan"

      - name: PHPStan
        run: tools/phpstan/vendor/bin/phpstan analyze --no-progress --error-format=checkstyle

  php-cs-fixer:
    name: PHP-CS-Fixer
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.4

      - name: Install php-cs-fixer
        uses: ramsey/composer-install@v2
        with:
          composer-options: "--working-dir=tools/php-cs-fixer"

      - name: PHP-CS-Fixer
        run: tools/php-cs-fixer/vendor/bin/php-cs-fixer fix --dry-run --diff --config=.php-cs-fixer.dist.php

  others:
    name: ðŸ§¹ Others Quality Checks
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.4

      - name: Download dependencies
        uses: ramsey/composer-install@v2

      - name: Lint Composer config
        shell: bash
        run: composer validate

      - name: Check that PSR is respected
        shell: bash
        run: composer dump-autoload --dev -o --dry-run --strict-psr

      - name: Check whether a PHP dependency is compromised
        shell: bash
        run: composer audit
